name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          VERBOSE: true
          
      - name: Get current time
        id: current_time
        run: echo "time=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
          
      - name: Check APK location
        run: |
          echo "Checking build output directory..."
          ls -R app/build/outputs/
          
      - name: Move APK
        run: |
          find app/build/outputs -name "*.apk" -exec cp {} ./CQUPT_Assistant_${{ steps.tag_version.outputs.new_tag }}.apk \;
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "CQUPT_Assistant_*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
          name: "Release ${{ steps.tag_version.outputs.new_tag }}"
          body: |
            ## 🚀 新版本发布
            
            ### 🔄 自动化发布
            - 版本: ${{ steps.tag_version.outputs.new_tag }}
            - 构建时间: ${{ steps.current_time.outputs.time }}
            
            ### 📝 更新内容
            ${{ steps.tag_version.outputs.changelog }}